name: splatam
channels:
  - nvidia
  - nvidia/label/cuda-11.8.0
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit=11.8
  - python=3.9
  - faiss-gpu=1.6.5
  - pytorch=2.1.2
  - torchaudio
  - torchvision=0.16.2
  - tqdm=4.65.0
  - Pillow
  - opencv
  - imageio
  - matplotlib
  - kornia
  - natsort
  - pyyaml
  - wandb
  - gxx_linux-64=10
  - pip
  - pip:
    - lpips
    - open3d==0.18.0
    - torchmetrics
    - cyclonedds
    - git+https://github.com/JonathonLuiten/diff-gaussian-rasterization-w-depth.git@cb65e4b86bc3bd8ed42174b72a62e8d3a3a71110